
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: appsrv-upload
  namespace: student-e-halilovic
  annotations:
    nfs.io/storage-path: "appsrv-upload"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nginx-www
  namespace: student-e-halilovic
  annotations:
    nfs.io/storage-path: "nginx-www"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi

